default: true

# Allow run-on lines for prose; rely on soft-wrap in editors.
MD013: false

# Allow line breaks in tables.
MD033:
  allowed_elements:
    - br

# Allow Emphasis in place of a heading
MD036: false
